Base add-Reviews files (6) added, without ReviewControllerTest
HaMeCTHuK/Filmorate pull request #15
Opened 2024-02-03 23:01 UTC by Alexey-Sutyrin

ReviewControllerTest file will be added later, when stable version will be finalized.
Please check if all current files are OK.
Thank you.

2024-02-04 05:20 UTC, HaMeCTHuK commented
Конфликта по сути нет, пересекается и дублируются некоторые методы. Новый метод findFilmById в  FilmDbStorage - данный метод уже реализован, называется public Film get(Long id). Если все ОК, мы просто новый метод пристрелим на решении конфликта. ТАк же нашел что ты не наследовал интерфейс для общих методов CRUD - public interface ReviewStorage. Так же добавил в интерфейс метод  findUserById, данный метод так же реализован в суперклассе как User get(long id).  Алексей можешь протестировать постман тесты с уже реализованым методом get. Если все ОК, мы просто новый метод пристрелим на решении конфликта. Я сегодня на работе, по возможности я подключусь к твоей ветке, попробую переделать. Логика реализации понятна, все супер! Я понимаю как вам сложно пока ориентироваться в моих писульках. Прошу понять и простить)

2024-02-04 05:34 UTC, litiychet requested changes
Все отлично, но есть небольшие замечания по коду.

2024-02-04 05:34 UTC, litiychet commented on src/main/java/ru/java/practicum/filmorate/storage/FilmStorage.java
> +    Film findFilmById(long id); // add-reviews - дополнение в файл
Для чего дополнительный метод для получения фильма по ID? Почему бы не использовать существующий get(Long id)?

2024-02-04 05:34 UTC, litiychet commented on src/main/java/ru/java/practicum/filmorate/storage/UserStorage.java
> +    User findUserById(long id); // add-reviews - дополнение в файл
Аналогичный вопрос, как и по findFilmById. Почему бы не использовать существующий get(Long id)?

2024-02-04 05:34 UTC, litiychet commented on src/main/java/ru/java/practicum/filmorate/service/ReviewService.java
> +public class ReviewService {
Не хватает методов для проверки входных ID review.

2024-02-04 05:34 UTC, litiychet commented on src/main/java/ru/java/practicum/filmorate/exception/ReviewDoesNotExistException.java
> +public class ReviewDoesNotExistException extends RuntimeException {
Думаю можно использовать исключение DataNotFoundException для проверки наличия ревью в БД.

2024-02-04 12:44 UTC, Alexey-Sutyrin commented
Temporary declined - временно отменяю pull request, по согласованию с тимлидом, потом вернём обратно доработанный.

2024-02-04 16:45 UTC, Alexey-Sutyrin commented on src/main/java/ru/java/practicum/filmorate/exception/ReviewDoesNotExistException.java
> +public class ReviewDoesNotExistException extends RuntimeException {
Переделал на DataNotFoundException, ReviewDoesNotExistException убрал из программы полностью, спасибо!

2024-02-04 16:48 UTC, Alexey-Sutyrin commented on src/main/java/ru/java/practicum/filmorate/storage/FilmStorage.java
> +    Film findFilmById(long id); // add-reviews - дополнение в файл
Переделал на get(Long id) из FilmDbStorage, убрал лишние изменения в FilmStorage и FilmDbStorage.
Работает, спасибо!

2024-02-04 16:48 UTC, Alexey-Sutyrin commented on src/main/java/ru/java/practicum/filmorate/storage/UserStorage.java
> +    User findUserById(long id); // add-reviews - дополнение в файл
Переделал на get(Long id) из FilmDbStorage, убрал лишние изменения в UserStorage и UserDbStorage.
Работает, спасибо!

2024-02-04 22:24 UTC, Alexey-Sutyrin commented
Needed to download this version of data

2024-02-04 22:54 UTC, Alexey-Sutyrin commented
1) get(Long id) добавлен вместо findFilmById \ findUserById в 6 разделах ReviewDbStorage и 4 связанных файлах (FilmDbStorage,FilmStorage,UserDbStorage,UserStorage) 
2) ReviewDoesNotExistException удален, заменен в использовании на стандартный DataNotFoundException
3) Переделка наследования через Abstract для ReviewStorage\ReviewService - в процессе.
4) Тесты ReviewControllerTest - в процессе.

Данный Pull Request отменен, уже не актуален.
Будет создан новый, синхронизированный с актуальным проектом.

2024-02-04 22:54 UTC, closed without merging

2024-02-05 22:11 UTC, Alexey-Sutyrin commented on src/main/java/ru/java/practicum/filmorate/service/ReviewService.java
> +public class ReviewService {
Переделал, спасибо.